<a href="http://mason.gmu.edu/~bpaudyal/bpphp/index.php">Home Page</a>

<h2> Lab Assignments</h2>
<ul>
  <li><a href="http://mason.gmu.edu/~bpaudyal/bpphp/LAB1/index.php">Assignmemt 1</a></li>
  <li><a href="http://mason.gmu.edu/~bpaudyal/bpphp/LAB2/index.php">Assignment 2</a></li>
  <li><a href="http://mason.gmu.edu/~bpaudyal/bpphp/LAB3/index.php">Assignment 3</a></li>
  <li><a href="http://mason.gmu.edu/~bpaudyal/bpphp/LAB4/index.php">Assignment 4</a></li>
</ul>

<h2> Lab Practica</h2>
        <ul>
            <li> <a href="prac1.html"> Practicum 1 </a></li>
            <li> <a href="prac2.html"> Practicum 2 </a></li>
        </ul>
